# Ejemplo de configuración para Jira Auto Task Creator
# ===================================================
# Copia este archivo a 'config.yml' y completa con tus credenciales

# Configuración de APIs y servicios
# =================================

# Configuración de Jira
jira:
  url: "https://tu-dominio.atlassian.net"
  email: "tu-email@ejemplo.com"
  api_token: "tu-token-de-api-de-jira-aqui"
  project_key: "PROJ"  # Clave del proyecto donde se crearán las tareas

# Configuración de OpenAI (opcional, para refinar tareas)
openai:
  api_key: "tu-api-key-de-openai-aqui"
  model: "gpt-4"  # gpt-4, gpt-3.5-turbo, etc.
  max_tokens: 2000
  temperature: 0.7

# Configuración de directorios
directories:
  task_folder: "task"
  unprocessed: "task/unprocessed"
  processed: "task/processed"
  without_formatting: "task/without-formatting"
  logs: "logs"

# Información sobre el uso
# ========================
# 
# Estructura de carpetas:
#   task/
#   ├── unprocessed/          # Tareas pendientes de procesar
#   │   └── {email}/
#   │       ├── tarea-1.yml
#   │       └── tarea-2.yml
#   ├── processed/            # Tareas ya procesadas en Jira
#   │   └── {email}/
#   │       ├── tarea-1-2025-10-13-14-30-45.yml
#   │       └── tarea-2-2025-10-13-14-31-12.yml
#   └── without-formatting/   # Tareas para refinar con OpenAI
#       └── {email}/
#           └── tarea-simple.yml
#
# Formato de archivos de tarea (.yml):
#   summary: "Nombre de la tarea"
#   description: "Descripción detallada"
#   issue_type: "Task"  # Task, Story, Bug, Epic, etc.
#   priority: "Medium"  # Highest, High, Medium, Low, Lowest
#
# Scripts disponibles:
#   - create-tasks.sh: Crea tareas en Jira desde unprocessed/
#   - refine-tasks.sh: Refina tareas usando OpenAI